version: '3'

services:


  Digital_chisel:
  
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "2000:2000"
    # volumes:


    runtime: nvidia
    environment:
     - NVIDIA_VISIBLE_DEVICES=0

